"""
SlopeSense — backend server (FastAPI edition)
Stores station readings and alerts in a real SQLite database, and serves
the dashboard + a typed JSON API built on FastAPI + Pydantic.

Run with:  pip install -r requirements.txt
           python3 main.py
Then open: http://localhost:8000

API docs (auto-generated by FastAPI) are available at:
http://localhost:8000/docs
"""

import os
import sqlite3
import datetime
from typing import List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException, Depends, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from ml_model import predict, feature_contributions
from notifications import send_alert
from imd_service import get_weather

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "landslide.db")
STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static")
PORT = 8000

# API key required for endpoints that write real sensor data (not the demo
# simulation controls, which stay open so the public dashboard still works).
# Override in production with:  set SLOPESENSE_API_KEY=your-real-key (Windows)
#                                export SLOPESENSE_API_KEY=your-real-key (macOS/Linux)
API_KEY = os.environ.get("SLOPESENSE_API_KEY", "demo-key-change-me")


def require_api_key(x_api_key: str = Header(default="")):
    if x_api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header")

STATIONS = [
    {"id": "nongpoh",  "name": "Nongpoh cutting",  "desc": "Steep road cutting, loose regolith",  "slope_factor": 0.65, "history_factor": 0.55, "rain72": 40, "intensity": 2.0, "moisture": 38, "lat": 25.86, "lon": 91.88, "slope_angle": 34, "elevation": 520, "drainage": 0.45, "soil_type": "Loose regolith"},
    {"id": "umsning",  "name": "Umsning bend",     "desc": "Sharp bend, past minor slips",        "slope_factor": 0.55, "history_factor": 0.70, "rain72": 45, "intensity": 2.0, "moisture": 40, "lat": 25.77, "lon": 91.90, "slope_angle": 31, "elevation": 610, "drainage": 0.38, "soil_type": "Weathered rock"},
    {"id": "byrnihat", "name": "Byrnihat descent", "desc": "Long descent, drainage congestion",   "slope_factor": 0.72, "history_factor": 0.40, "rain72": 35, "intensity": 1.5, "moisture": 35, "lat": 26.04, "lon": 91.91, "slope_angle": 39, "elevation": 430, "drainage": 0.30, "soil_type": "Clay-rich soil"},
    {"id": "barapani", "name": "Barapani ridge",   "desc": "Ridge-line, high exposure",           "slope_factor": 0.60, "history_factor": 0.35, "rain72": 38, "intensity": 1.8, "moisture": 33, "lat": 25.68, "lon": 91.90, "slope_angle": 35, "elevation": 970, "drainage": 0.62, "soil_type": "Residual soil"},
    {"id": "jorabat",  "name": "Jorabat junction", "desc": "Lower gradient, denser drainage",     "slope_factor": 0.35, "history_factor": 0.25, "rain72": 30, "intensity": 1.2, "moisture": 30, "lat": 26.12, "lon": 91.87, "slope_angle": 19, "elevation": 160, "drainage": 0.72, "soil_type": "Dense alluvium"},
]

RISK_LEVELS = [
    (0.30, "Low"),
    (0.55, "Moderate"),
    (0.75, "High"),
    (1.01, "Critical"),
]


# ---------------------------------------------------------------------------
# Pydantic response models (typed API contract, replaces hand-rolled JSON)
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    ok: bool
    ai_model: str
    database: str


class ReadingPoint(BaseModel):
    tick: int
    risk: float


class AIFactor(BaseModel):
    factor: str
    impact: float


class Station(BaseModel):
    id: str
    name: str
    desc: str
    slope_factor: float
    history_factor: float
    lat: float
    lon: float
    slope_angle: float
    elevation: float
    drainage: float
    soil_type: str
    rain72: float
    intensity: float
    moisture: float
    risk: float
    level: str
    rain24: float
    forecast6h: float
    tilt_rate: float
    ai_probability: float
    ai_level: str
    ai_factors: List[AIFactor]
    prediction_window: str
    action: str
    history: List[ReadingPoint]


class Alert(BaseModel):
    id: int
    station_id: str
    station_name: str
    level: str
    message: str
    ts: str


class StateResponse(BaseModel):
    stations: List[Station]
    alerts: List[Alert]
    tick: int


class TelemetryInput(BaseModel):
    """Payload a real sensor / weather-feed integration would POST."""
    station_id: str = Field(..., description="Must match an existing station id, e.g. 'nongpoh'")
    rain72: float = Field(..., ge=0, description="Cumulative rainfall over the last 72h, mm")
    intensity: float = Field(..., ge=0, description="Current rainfall intensity, mm/hr")
    moisture: float = Field(..., ge=0, le=100, description="Soil moisture, percent")


class TelemetryResult(BaseModel):
    station_id: str
    risk: float
    level: str
    alert_fired: bool
    notification: Optional[dict] = None


# ---------------------------------------------------------------------------
# Business logic (unchanged from the stdlib version)
# ---------------------------------------------------------------------------

def classify(risk):
    for cap, label in RISK_LEVELS:
        if risk <= cap:
            return label
    return "Critical"


def compute_risk(slope_factor, history_factor, rain72, intensity, moisture):
    rain_norm = min(rain72 / 150, 1)
    intensity_norm = min(intensity / 25, 1)
    moisture_norm = min(moisture / 100, 1)
    risk = (rain_norm * 0.30) + (intensity_norm * 0.30) + (slope_factor * 0.20) + (moisture_norm * 0.10) + (history_factor * 0.10)
    return min(risk, 1.0)
def get_open_meteo_data(latitude, longitude):
    data = get_weather(latitude, longitude)

    if not data:
        return None

    return {
        "temperature": data.get("temperature", 0),
        "humidity": data.get("humidity", 0),
        "current_rain": data.get("current_rain", 0),
        "rain72": data.get("rain72", 0)
    }
def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    fresh = not os.path.exists(DB_PATH)
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS stations (
        id TEXT PRIMARY KEY, name TEXT, desc TEXT,
        slope_factor REAL, history_factor REAL, lat REAL, lon REAL, slope_angle REAL, elevation REAL, drainage REAL, soil_type TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS readings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        station_id TEXT, tick INTEGER,
        rain72 REAL, intensity REAL, moisture REAL, risk REAL,
        ts TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS alerts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        station_id TEXT, station_name TEXT, level TEXT, message TEXT, ts TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT)""")
    conn.commit()

    # Lightweight schema migration for databases created by the older prototype.
    existing_cols = {r[1] for r in cur.execute("PRAGMA table_info(stations)").fetchall()}
    migrations = {"lat":"REAL", "lon":"REAL", "slope_angle":"REAL", "elevation":"REAL", "drainage":"REAL", "soil_type":"TEXT"}
    for col, typ in migrations.items():
        if col not in existing_cols:
            cur.execute(f"ALTER TABLE stations ADD COLUMN {col} {typ}")
    cur.execute("UPDATE stations SET lat=25.86,lon=91.88,slope_angle=34,elevation=520,drainage=0.45,soil_type='Loose regolith' WHERE id='nongpoh' AND lat IS NULL")
    cur.execute("UPDATE stations SET lat=25.77,lon=91.90,slope_angle=31,elevation=610,drainage=0.38,soil_type='Weathered rock' WHERE id='umsning' AND lat IS NULL")
    cur.execute("UPDATE stations SET lat=26.04,lon=91.91,slope_angle=39,elevation=430,drainage=0.30,soil_type='Clay-rich soil' WHERE id='byrnihat' AND lat IS NULL")
    cur.execute("UPDATE stations SET lat=25.68,lon=91.90,slope_angle=35,elevation=970,drainage=0.62,soil_type='Residual soil' WHERE id='barapani' AND lat IS NULL")
    cur.execute("UPDATE stations SET lat=26.12,lon=91.87,slope_angle=19,elevation=160,drainage=0.72,soil_type='Dense alluvium' WHERE id='jorabat' AND lat IS NULL")
    conn.commit()

    cur.execute("SELECT COUNT(*) as c FROM stations")
    if cur.fetchone()["c"] == 0:
        for s in STATIONS:
            cur.execute(
                "INSERT INTO stations (id,name,desc,slope_factor,history_factor,lat,lon,slope_angle,elevation,drainage,soil_type) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                (s["id"], s["name"], s["desc"], s["slope_factor"], s["history_factor"], s["lat"], s["lon"], s["slope_angle"], s["elevation"], s["drainage"], s["soil_type"]),
            )
        conn.commit()

    cur.execute("SELECT COUNT(*) as c FROM readings")
    if cur.fetchone()["c"] == 0:
        seed_baseline(conn)

    cur.execute("SELECT COUNT(*) as c FROM meta WHERE key='tick'")
    if cur.fetchone()["c"] == 0:
        cur.execute("INSERT INTO meta (key,value) VALUES ('tick','0')")
        conn.commit()

    conn.close()
    if fresh:
        print(f"Created new database at {DB_PATH}")


def seed_baseline(conn):
    cur = conn.cursor()
    ts = datetime.datetime.now().isoformat()
    for s in STATIONS:
        risk = compute_risk(s["slope_factor"], s["history_factor"], s["rain72"], s["intensity"], s["moisture"])
        cur.execute(
            "INSERT INTO readings (station_id,tick,rain72,intensity,moisture,risk,ts) VALUES (?,?,?,?,?,?,?)",
            (s["id"], 0, s["rain72"], s["intensity"], s["moisture"], risk, ts),
        )
    conn.commit()


def get_state():
    conn = get_conn()
    cur = conn.cursor()

    cur.execute("SELECT * FROM stations")
    stations = [dict(r) for r in cur.fetchall()]

    for s in stations:
        cur.execute(
            "SELECT * FROM readings WHERE station_id=? ORDER BY tick DESC LIMIT 1",
            (s["id"],),
        )
        latest = cur.fetchone()
        s["rain72"] = latest["rain72"]
        s["intensity"] = latest["intensity"]
        s["moisture"] = latest["moisture"]
        s["risk"] = latest["risk"]
        s["level"] = classify(latest["risk"])
        s["rain24"] = min(s["rain72"] * 0.48, s["rain72"])
        s["forecast6h"] = min(180, s["intensity"] * 3.5 + s["rain72"] * 0.08)
        s["tilt_rate"] = round(max(0.05, (s["risk"] * 4.5) - 1.0), 2)
        features = {"rain24": s["rain24"], "rain72": s["rain72"], "intensity": s["intensity"], "moisture": s["moisture"], "slope_angle": s.get("slope_angle") or 30, "elevation": s.get("elevation") or 500, "drainage": s.get("drainage") or 0.5, "history": s["history_factor"], "tilt_rate": s["tilt_rate"], "forecast6h": s["forecast6h"]}
        s["ai_probability"] = predict(features)
        s["ai_level"] = classify(s["ai_probability"])
        s["ai_factors"] = feature_contributions(features)
        s["prediction_window"] = "next 6 hours"
        if s["ai_level"] == "Critical":
            s["action"] = "Issue immediate warning and inspect/restrict the exposed road section."
        elif s["ai_level"] == "High":
            s["action"] = "Increase monitoring and inspect slope movement and drainage."
        elif s["ai_level"] == "Moderate":
            s["action"] = "Continue enhanced monitoring; check drainage after heavy rain."
        else:
            s["action"] = "Normal monitoring."

        cur.execute(
            "SELECT tick, risk FROM readings WHERE station_id=? ORDER BY tick DESC LIMIT 25",
            (s["id"],),
        )
        hist = [dict(r) for r in cur.fetchall()]
        hist.reverse()
        s["history"] = hist

    cur.execute("SELECT * FROM alerts ORDER BY id DESC LIMIT 50")
    alerts = [dict(r) for r in cur.fetchall()]

    cur.execute("SELECT value FROM meta WHERE key='tick'")
    tick = int(cur.fetchone()["value"])

    conn.close()
    return {"stations": stations, "alerts": alerts, "tick": tick}


def simulate_step():
    conn = get_conn()
    cur = conn.cursor()
    ts = datetime.datetime.now().isoformat()

    cur.execute("SELECT value FROM meta WHERE key='tick'")
    tick = int(cur.fetchone()["value"]) + 1

    cur.execute("SELECT * FROM stations")
    stations = [dict(r) for r in cur.fetchall()]

    for s in stations:
        cur.execute(
            "SELECT * FROM readings WHERE station_id=? ORDER BY tick DESC LIMIT 1",
            (s["id"],),
        )
        latest = dict(cur.fetchone())
        prior_level = classify(latest["risk"])

        storm_factor = 1 + s["slope_factor"] * 0.6 + s["history_factor"] * 0.4
        new_intensity = min(latest["intensity"] + 0.9 * storm_factor, 30)
        new_rain72 = min(latest["rain72"] + new_intensity * 0.6, 220)
        new_moisture = min(latest["moisture"] + 1.4, 95)
        new_risk = compute_risk(s["slope_factor"], s["history_factor"], new_rain72, new_intensity, new_moisture)
        new_level = classify(new_risk)

        cur.execute(
            "INSERT INTO readings (station_id,tick,rain72,intensity,moisture,risk,ts) VALUES (?,?,?,?,?,?,?)",
            (s["id"], tick, new_rain72, new_intensity, new_moisture, new_risk, ts),
        )

        if new_level != prior_level and new_level in ("High", "Critical"):
            message = (
                f"risk escalated to CRITICAL ({new_risk*100:.0f}%) — recommend immediate advisory"
                if new_level == "Critical"
                else f"risk escalated to HIGH ({new_risk*100:.0f}%) — heightened monitoring advised"
            )
            cur.execute(
                "INSERT INTO alerts (station_id,station_name,level,message,ts) VALUES (?,?,?,?,?)",
                (s["id"], s["name"], new_level, message, ts),
            )
            send_alert(s["name"], new_level, message)

    cur.execute("UPDATE meta SET value=? WHERE key='tick'", (str(tick),))
    conn.commit()
    conn.close()


def ingest_reading(station_id: str, rain72: float, intensity: float, moisture: float) -> dict:
    """Record a real (non-simulated) reading pushed by a sensor/weather feed."""
    conn = get_conn()
    cur = conn.cursor()

    cur.execute("SELECT * FROM stations WHERE id=?", (station_id,))
    station = cur.fetchone()
    if not station:
        conn.close()
        raise ValueError(f"Unknown station_id '{station_id}'")
    station = dict(station)

    cur.execute("SELECT value FROM meta WHERE key='tick'")
    tick = int(cur.fetchone()["value"]) + 1

    cur.execute(
        "SELECT * FROM readings WHERE station_id=? ORDER BY tick DESC LIMIT 1",
        (station_id,),
    )
    latest = cur.fetchone()
    prior_level = classify(latest["risk"]) if latest else "Low"

    new_risk = compute_risk(station["slope_factor"], station["history_factor"], rain72, intensity, moisture)
    new_level = classify(new_risk)
    ts = datetime.datetime.now().isoformat()

    cur.execute(
        "INSERT INTO readings (station_id,tick,rain72,intensity,moisture,risk,ts) VALUES (?,?,?,?,?,?,?)",
        (station_id, tick, rain72, intensity, moisture, new_risk, ts),
    )

    alert_fired = False
    notification = None
    if new_level != prior_level and new_level in ("High", "Critical"):
        message = (
            f"risk escalated to CRITICAL ({new_risk*100:.0f}%) — recommend immediate advisory"
            if new_level == "Critical"
            else f"risk escalated to HIGH ({new_risk*100:.0f}%) — heightened monitoring advised"
        )
        cur.execute(
            "INSERT INTO alerts (station_id,station_name,level,message,ts) VALUES (?,?,?,?,?)",
            (station_id, station["name"], new_level, message, ts),
        )
        notification = send_alert(station["name"], new_level, message)
        alert_fired = True

    cur.execute("UPDATE meta SET value=? WHERE key='tick'", (str(tick),))
    conn.commit()
    conn.close()

    return {"risk": new_risk, "level": new_level, "alert_fired": alert_fired, "notification": notification}


def reset_state():
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("DELETE FROM readings")
    cur.execute("DELETE FROM alerts")
    cur.execute("UPDATE meta SET value='0' WHERE key='tick'")
    conn.commit()
    seed_baseline(conn)
    conn.close()


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

app = FastAPI(
    title="SlopeSense — Landslide Early Warning API",
    description="Typed REST API for the SlopeSense landslide monitoring prototype.",
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def on_startup():
    init_db()


@app.get("/", include_in_schema=False)
def serve_index():
    return FileResponse(os.path.join(STATIC_DIR, "index.html"))


@app.get("/api/health", response_model=HealthResponse)
def health():
    return HealthResponse(ok=True, ai_model="logistic_regression_demo", database=DB_PATH)


@app.get("/api/state", response_model=StateResponse)
def api_state():
    try:
        return get_state()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read state: {e}")

@app.get("/api/weather/{station_id}")
def api_weather(station_id: str):

    station = next(
        (s for s in STATIONS if s["id"] == station_id),
        None
    )

    if not station:
        raise HTTPException(
            status_code=404,
            detail="Station not found"
        )

    weather = get_open_meteo_data(
        station["lat"],
        station["lon"]
    )

    if weather is None:
        raise HTTPException(
            status_code=500,
            detail="Could not fetch weather data"
        )

    return {
        "station_id": station_id,
        "station_name": station["name"],
        "latitude": station["lat"],
        "longitude": station["lon"],
        "weather": weather
    }
@app.get("/api/live-risk/{station_id}")
def api_live_risk(station_id: str):

    station = next(
        (s for s in STATIONS if s["id"] == station_id),
        None
    )

    if not station:
        raise HTTPException(
            status_code=404,
            detail="Station not found"
        )

    weather = get_open_meteo_data(
        station["lat"],
        station["lon"]
    )

    if weather is None:
        raise HTTPException(
            status_code=500,
            detail="Could not fetch weather data"
        )

    # Real rainfall from Open-Meteo
    rain72 = weather["rain72"]

    # Existing station values
    intensity = station["intensity"]
    moisture = station["moisture"]

    # Calculate landslide risk
    risk = compute_risk(
       station["slope_factor"],
       station["history_factor"],
       rain72,
       intensity,
       moisture
    )

    risk_level = classify(risk)

    return {
        "station_id": station_id,
        "station_name": station["name"],
        "weather": {
            "temperature": weather["temperature"],
            "humidity": weather["humidity"],
            "current_rain": weather["current_rain"],
            "rain72": rain72
        },
        "landslide_risk": {
            "score": round(risk, 3),
            "level": risk_level
        }
    }
@app.post("/api/simulate/step", response_model=StateResponse)
def api_simulate_step():
    try:
        simulate_step()
        return get_state()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Simulation step failed: {e}")


@app.post("/api/reset", response_model=StateResponse, dependencies=[Depends(require_api_key)])
def api_reset():
    try:
        reset_state()
        return get_state()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Reset failed: {e}")


@app.post("/api/telemetry", response_model=TelemetryResult, dependencies=[Depends(require_api_key)])
def api_telemetry(data: TelemetryInput):
    """
    Ingest a real sensor / weather-feed reading for one station.
    Requires header:  X-API-Key: <SLOPESENSE_API_KEY>
    This is the integration point a real rain gauge, soil-moisture probe,
    or third-party weather API would call instead of the simulator.
    """
    try:
        result = ingest_reading(data.station_id, data.rain72, data.intensity, data.moisture)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ingestion failed: {e}")
    return TelemetryResult(station_id=data.station_id, **result)


# Mount the static folder for any other assets referenced by index.html
# (kept after the explicit routes above so /, /api/* take priority)
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


if __name__ == "__main__":
    init_db()
    print("SlopeSense backend (FastAPI) running")
    print(f"Database: {DB_PATH}")
    print(f"Open http://localhost:{PORT} in your browser")
    print(f"API docs: http://localhost:{PORT}/docs")
    print(f"Telemetry ingestion API key (X-API-Key header): {API_KEY}")
    if API_KEY == "demo-key-change-me":
        print("  (set the SLOPESENSE_API_KEY environment variable to use a real key)")
    uvicorn.run(app, host="0.0.0.0", port=PORT)

